services:
  zoerb_filerev.templating.asset.path_package:
    abstract: true
    class: Zoerb\Bundle\FilerevBundle\Templating\Asset\PathPackage
    arguments: [@request,"","","","",""]
    scope: request

  zoerb_filerev.templating.asset.url_package:
    abstract: true
    class: Zoerb\Bundle\FilerevBundle\Templating\Asset\UrlPackage
    arguments: ["","","","","",""]