services:
  zoerb_filerev.templating.asset.path_package:
    public: false
    class: Zoerb\Bundle\FilerevBundle\Templating\Asset\PathPackage
    arguments: [@request,"","","",""]
    scope: request

  zoerb_filerev.templating.asset.url_package:
    public: false
    class: Zoerb\Bundle\FilerevBundle\Templating\Asset\UrlPackage
    arguments: ["","","","",""]
